import { describe, expect, it } from 'vitest'
import { createMemoryDatabase, InMemoryPlayerRepository } from '../repositories/InMemoryPlayerRepository'
import { PlayerStateService } from '../players/PlayerStateService'
import { PresenceService } from './PresenceService'
import { FriendsService } from './FriendsService'
import { GuildService } from '../guilds/GuildService'
import { ChatService } from '../chat/ChatService'
import { EconomyService } from '../economy/EconomyService'
import { RoomManager } from '../rooms/RoomManager'
import type { ServerMessage } from '../../shared/protocol'

async function setup(names = ['Alice', 'Bob', 'Cara', 'Danylo']) {
  const database = createMemoryDatabase(); const repository = new InMemoryPlayerRepository(database); const players = new PlayerStateService(repository)
  let clock = 10_000; const now = () => clock; const advance = (ms: number) => { clock += ms }
  const presence = new PresenceService(); const guilds = new GuildService(repository, presence, now); const friends = new FriendsService(repository, presence, now); const chat = new ChatService(repository, presence, now); const economy = new EconomyService(repository, now)
  for (const name of names) { const id = name.toLowerCase(); await players.getOrCreate({ playerId: id, character: { name, classId: name === 'Bob' ? 'blacksmith' : 'alchemist', level: 10 } }); presence.set(id, 'CITY'); economy.setAvailability(id, true) }
  await players.awardProgression('alice', 10, 0, 2_000, 'fund-alice')
  return { database, repository, players, presence, guilds, friends, chat, economy, now, advance }
}
async function createGuild(c: Awaited<ReturnType<typeof setup>>, operation = 'create') { return c.guilds.create('alice', { name: 'Wardens', tag: 'WARD', description: 'Rift guild' }, operation) }
async function addRecruit(c: Awaited<ReturnType<typeof setup>>, player = 'bob') { const application = await c.guilds.apply(player, (await createGuild(c)).guild!.id, 'Ready', `apply-${player}`); void application; const id = (await c.guilds.state('alice')).applications.find((value) => value.player.playerId === player)!.id; await c.guilds.reviewApplication('alice', id, true, `accept-${player}`) }

describe('Phase 6 Guild', () => {
  it('create guild costs configured coins', async () => { const c = await setup(); await createGuild(c); expect((await c.players.snapshot('alice')).availableCoins).toBe(1500); expect((await c.players.ledger('alice')).at(-1)?.reason).toBe('GUILD_CREATION') })
  it('insufficient coins cannot create guild', async () => { const c = await setup(); await expect(c.guilds.create('bob', { name: 'Poor Guild', tag: 'POOR' }, 'x')).rejects.toThrow() })
  it('guild name is unique case-insensitively', async () => { const c = await setup(); await createGuild(c); await c.players.awardProgression('bob', 10, 0, 1000, 'fund'); await expect(c.guilds.create('bob', { name: 'wArDeNs', tag: 'OTHER' }, 'x')).rejects.toThrow() })
  it('guild tag is unique case-insensitively', async () => { const c = await setup(); await createGuild(c); await c.players.awardProgression('bob', 10, 0, 1000, 'fund'); await expect(c.guilds.create('bob', { name: 'Other', tag: 'ward' }, 'x')).rejects.toThrow() })
  it('player cannot join two guilds', async () => { const c = await setup(); await createGuild(c); await c.players.awardProgression('bob', 10, 0, 1000, 'fund'); await c.guilds.create('bob', { name: 'Second', tag: 'SEC' }, 'b'); await expect(c.guilds.apply('bob', (await c.guilds.search('Wardens'))[0].id, '', 'a')).rejects.toThrow() })
  it('creator becomes sole leader', async () => { const state = await createGuild(await setup()); expect(state.selfRank).toBe('LEADER'); expect(state.members.filter((value) => value.rank === 'LEADER')).toHaveLength(1) })
  it('application accept creates Recruit', async () => { const c = await setup(); await addRecruit(c); expect((await c.guilds.state('bob')).selfRank).toBe('RECRUIT') })
  it('application reject leaves player guildless', async () => { const c = await setup(); const guildId = (await createGuild(c)).guild!.id; await c.guilds.apply('bob', guildId, '', 'a'); const id = (await c.guilds.state('alice')).applications[0].id; await c.guilds.reviewApplication('alice', id, false, 'r'); expect((await c.guilds.state('bob')).guild).toBeNull() })
  it('invite accept creates Recruit membership', async () => { const c = await setup(); await createGuild(c); await c.guilds.invite('alice', 'Bob', 'i'); const invite = (await c.guilds.state('bob')).invites[0]; await c.guilds.respondInvite('bob', invite.id, true, 'a'); expect((await c.guilds.state('bob')).selfRank).toBe('RECRUIT') })
  it('invite decline keeps player guildless', async () => { const c = await setup(); await createGuild(c); await c.guilds.invite('alice', 'Bob', 'i'); const invite = (await c.guilds.state('bob')).invites[0]; await c.guilds.respondInvite('bob', invite.id, false, 'd'); expect((await c.guilds.state('bob')).guild).toBeNull() })
  it('only permitted ranks accept applications', async () => { const c = await setup(); await addRecruit(c); const guildId = (await c.guilds.state('alice')).guild!.id; await c.guilds.apply('cara', guildId, '', 'c'); const application = (await c.guilds.state('alice')).applications[0]; await expect(c.guilds.reviewApplication('bob', application.id, true, 'bad')).rejects.toThrow() })
  it('officer cannot kick leader', async () => { const c = await setup(); await addRecruit(c); await c.guilds.setRank('alice', 'bob', 'OFFICER', 'rank'); await expect(c.guilds.kick('bob', 'alice', 'kick')).rejects.toThrow() })
  it('leadership transfer is atomic and leaves one leader', async () => { const c = await setup(); await addRecruit(c); await c.guilds.transferLeadership('alice', 'bob', 'transfer'); const state = await c.guilds.state('bob'); expect(state.guild?.leaderPlayerId).toBe('bob'); expect(state.members.filter((value) => value.rank === 'LEADER')).toHaveLength(1); expect(state.members.find((value) => value.playerId === 'alice')?.rank).toBe('OFFICER') })
  it('leader cannot leave without transfer or disband', async () => { const c = await setup(); await createGuild(c); await expect(c.guilds.leave('alice', 'leave')).rejects.toThrow() })
  it('cannot disband non-empty storage', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); await c.guilds.deposit('alice', item.entryId, 1, 'dep'); await expect(c.guilds.disband('alice', true, 'disband')).rejects.toThrow() })
  it('successful disband requires explicit confirmation', async () => { const c = await setup(); await createGuild(c); await expect(c.guilds.disband('alice', false, 'no')).rejects.toThrow(); await c.guilds.disband('alice', true, 'yes'); expect((await c.guilds.state('alice')).guild).toBeNull() })
  it('duplicate membership is prevented across application and invite', async () => { const c = await setup(); await addRecruit(c); await expect(c.guilds.invite('alice', 'Bob', 'again')).rejects.toThrow(); expect((await c.guilds.state('alice')).members.filter((value) => value.playerId === 'bob')).toHaveLength(1) })
  it('guild max members is enforced', async () => { const names = ['Alice', ...Array.from({ length: 50 }, (_, index) => `P${index}`)]; const c = await setup(names); const guildId = (await createGuild(c)).guild!.id; await c.repository.socialTransact('alice', 'fill', 'TEST', (state) => { for (const name of names.slice(1, 50)) state.guildMembers.set(name.toLowerCase(), { guildId, playerId: name.toLowerCase(), rank: 'RECRUIT', joinedAt: c.now() }) }); await c.guilds.apply('p49', guildId, '', 'apply-full'); const application = (await c.guilds.state('alice')).applications.find((value) => value.player.playerId === 'p49')!; await expect(c.guilds.reviewApplication('alice', application.id, true, 'full')).rejects.toThrow() })
})

describe('Phase 6 Guild Storage', () => {
  it('member deposit works', async () => { const c = await setup(); await addRecruit(c); await c.guilds.setRank('alice', 'bob', 'MEMBER', 'rank'); const item = await c.players.addItemForTesting('bob', 'rift_iron', 5); await c.guilds.deposit('bob', item.entryId, 5, 'd'); expect((await c.guilds.storage('bob')).items.some((value) => value.itemId === 'rift_iron')).toBe(true) })
  it('recruit deposit follows default permission', async () => { const c = await setup(); await addRecruit(c); const item = await c.players.addItemForTesting('bob', 'rift_iron', 2); await c.guilds.deposit('bob', item.entryId, 2, 'd'); expect((await c.guilds.storage('bob')).items).toHaveLength(1) })
  it('recruit withdraw is rejected by default', async () => { const c = await setup(); await addRecruit(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 2); const storage = await c.guilds.deposit('alice', item.entryId, 2, 'd'); await expect(c.guilds.withdraw('bob', storage.items[0].id, 1, 'w')).rejects.toThrow() })
  it('leader can change rank storage permission', async () => { const c = await setup(); await addRecruit(c); await c.guilds.updatePermission('alice', 'RECRUIT', { canDeposit: true, canWithdraw: true }, 'p'); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); await c.guilds.withdraw('bob', storage.items[0].id, 1, 'w'); expect(await c.players.countItem('bob', 'rift_iron')).toBeGreaterThan(0) })
  it('stack partial deposit works', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 10); await c.guilds.deposit('alice', item.entryId, 4, 'd'); expect((await c.guilds.storage('alice')).items[0].quantity).toBe(4); expect((await c.players.snapshot('alice')).inventory.find((value) => value.entryId === item.entryId)?.quantity).toBe(6) })
  it('stack partial withdraw works', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 10); const storage = await c.guilds.deposit('alice', item.entryId, 10, 'd'); await c.guilds.withdraw('alice', storage.items[0].id, 3, 'w'); expect((await c.guilds.storage('alice')).items[0].quantity).toBe(7) })
  it('individual equipment identity is preserved', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'crafted_alchemist_weapon', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); await c.guilds.withdraw('alice', storage.items[0].id, 1, 'w'); expect((await c.players.snapshot('alice')).inventory.some((value) => value.entryId === item.entryId)).toBe(true) })
  it('deposit removes personal ownership', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'crafted_alchemist_weapon', 1); await c.guilds.deposit('alice', item.entryId, 1, 'd'); expect((await c.players.snapshot('alice')).inventory.some((value) => value.entryId === item.entryId)).toBe(false) })
  it('withdraw assigns personal ownership', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'crafted_alchemist_weapon', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); await c.guilds.withdraw('alice', storage.items[0].id, 1, 'w'); expect((await c.players.snapshot('alice')).inventory.some((value) => value.entryId === item.entryId)).toBe(true) })
  it('equipped item cannot deposit', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'crafted_alchemist_weapon', 1); await c.players.equip('alice', item.entryId); await expect(c.guilds.deposit('alice', item.entryId, 1, 'd')).rejects.toThrow() })
  it('market escrow cannot deposit', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); await c.economy.createSellOrder('alice', item.entryId, 1, 5, 'sell'); await expect(c.guilds.deposit('alice', item.entryId, 1, 'd')).rejects.toThrow() })
  it('trade escrow cannot deposit', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); const trade = await c.economy.requestTrade('alice', 'Bob', 'r'); await c.economy.acceptTrade('bob', trade.id, 'a'); await c.economy.updateTradeOffer('alice', trade.id, { items: [{ entryId: item.entryId, quantity: 1 }], coins: 0 }, 'u'); await expect(c.guilds.deposit('alice', item.entryId, 1, 'd')).rejects.toThrow() })
  it('duplicate deposit is idempotent', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 2); await Promise.all([c.guilds.deposit('alice', item.entryId, 2, 'same'), c.guilds.deposit('alice', item.entryId, 2, 'same')]); expect((await c.guilds.storage('alice')).items.reduce((sum, value) => sum + value.quantity, 0)).toBe(2) })
  it('duplicate withdraw is idempotent', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 2); const storage = await c.guilds.deposit('alice', item.entryId, 2, 'd'); await Promise.all([c.guilds.withdraw('alice', storage.items[0].id, 2, 'same'), c.guilds.withdraw('alice', storage.items[0].id, 2, 'same')]); expect((await c.guilds.storage('alice')).items).toHaveLength(0) })
  it('concurrent withdraw cannot duplicate item', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'crafted_alchemist_weapon', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); const results = await Promise.allSettled([c.guilds.withdraw('alice', storage.items[0].id, 1, 'w1'), c.guilds.withdraw('alice', storage.items[0].id, 1, 'w2')]); expect(results.filter((value) => value.status === 'fulfilled')).toHaveLength(1); expect((await c.players.snapshot('alice')).inventory.filter((value) => value.entryId === item.entryId)).toHaveLength(1) })
  it('storage log is written on deposit', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); await c.guilds.deposit('alice', item.entryId, 1, 'd'); expect((await c.guilds.history('alice'))[0].action).toBe('DEPOSIT') })
  it('storage log is written on withdraw', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); await c.guilds.withdraw('alice', storage.items[0].id, 1, 'w'); expect((await c.guilds.history('alice'))[0].action).toBe('WITHDRAW') })
  it('guild storage asset cannot be sold or traded directly', async () => { const c = await setup(); await createGuild(c); const item = await c.players.addItemForTesting('alice', 'rift_iron', 1); const storage = await c.guilds.deposit('alice', item.entryId, 1, 'd'); await expect(c.economy.createSellOrder('alice', storage.items[0].id, 1, 5, 's')).rejects.toThrow(); const trade = await c.economy.requestTrade('alice', 'Bob', 'r'); await c.economy.acceptTrade('bob', trade.id, 'a'); await expect(c.economy.updateTradeOffer('alice', trade.id, { items: [{ entryId: storage.items[0].id, quantity: 1 }], coins: 0 }, 'u')).rejects.toThrow() })
})

describe('Phase 6 Friends and Blocking', () => {
  it('creates friend request', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); expect((await c.friends.state('bob')).incoming).toHaveLength(1) })
  it('accept creates one friendship', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); const request = (await c.friends.state('bob')).incoming[0]; await c.friends.respond('bob', request.id, true, 'a'); expect((await c.friends.state('alice')).friends.map((value) => value.playerId)).toContain('bob') })
  it('reject does not create friendship', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); const request = (await c.friends.state('bob')).incoming[0]; await c.friends.respond('bob', request.id, false, 'd'); expect((await c.friends.state('alice')).friends).toHaveLength(0) })
  it('duplicate pending request is prevented', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); await expect(c.friends.sendRequest('alice', 'Bob', 'r2')).rejects.toThrow() })
  it('friendship is symmetric', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); const request = (await c.friends.state('bob')).incoming[0]; await c.friends.respond('bob', request.id, true, 'a'); expect((await c.friends.state('alice')).friends[0].playerId).toBe('bob'); expect((await c.friends.state('bob')).friends[0].playerId).toBe('alice') })
  it('remove friendship affects both sides', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); const request = (await c.friends.state('bob')).incoming[0]; await c.friends.respond('bob', request.id, true, 'a'); await c.friends.remove('alice', 'bob', 'x'); expect((await c.friends.state('bob')).friends).toHaveLength(0) })
  it('cannot friend self', async () => { const c = await setup(); await expect(c.friends.sendRequest('alice', 'Alice', 'r')).rejects.toThrow() })
  it('blocked player cannot send friend request', async () => { const c = await setup(); await c.friends.block('bob', 'Alice', 'b'); await expect(c.friends.sendRequest('alice', 'Bob', 'r')).rejects.toThrow() })
  it('blocked player cannot send private message', async () => { const c = await setup(); await c.friends.block('bob', 'Alice', 'b'); await expect(c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'hello' }, 'm')).rejects.toThrow() })
})

describe('Phase 6 Chat', () => {
  it('global message has server realtime payload', async () => { const c = await setup(); const message = await c.chat.send('alice', { channel: 'GLOBAL', text: 'Hello' }, 'g'); expect(message).toMatchObject({ channel: 'GLOBAL', senderId: 'alice', createdAt: c.now() }) })
  it('guild message recipients are only guild members', async () => { const c = await setup(); await addRecruit(c); const message = await c.chat.send('alice', { channel: 'GUILD', text: 'Guild' }, 'g'); expect((await c.chat.recipients(message)).sort()).toEqual(['alice', 'bob']) })
  it('non-member cannot send guild message', async () => { const c = await setup(); await createGuild(c); await expect(c.chat.send('bob', { channel: 'GUILD', text: 'No' }, 'g')).rejects.toThrow() })
  it('group chat remains room scoped', async () => { const c = await setup(); const message = c.chat.groupMessage('alice', 'room-a', 'Alice', 'Group'); expect(message).toMatchObject({ channel: 'GROUP', roomId: 'room-a' }) })
  it('private message recipient is correct', async () => { const c = await setup(); const message = await c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'Private' }, 'p'); expect((await c.chat.recipients(message)).sort()).toEqual(['alice', 'bob']) })
  it('blocked private message is rejected', async () => { const c = await setup(); await c.friends.block('bob', 'Alice', 'b'); await expect(c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'Private' }, 'p')).rejects.toThrow() })
  it('max length is enforced', async () => { const c = await setup(); await expect(c.chat.send('alice', { channel: 'GLOBAL', text: 'x'.repeat(301) }, 'g')).rejects.toThrow() })
  it('whitespace message is rejected', async () => { const c = await setup(); await expect(c.chat.send('alice', { channel: 'GLOBAL', text: '   ' }, 'g')).rejects.toThrow() })
  it('client timestamp is ignored in favor of server time', async () => { const c = await setup(); const message = await c.chat.send('alice', { channel: 'GLOBAL', text: 'Now', ...({ createdAt: 1 } as object) }, 'g'); expect(message.createdAt).toBe(c.now()) })
  it('global rate limit is two seconds', async () => { const c = await setup(); await c.chat.send('alice', { channel: 'GLOBAL', text: 'One' }, '1'); await expect(c.chat.send('alice', { channel: 'GLOBAL', text: 'Two' }, '2')).rejects.toThrow(); c.advance(2000); await expect(c.chat.send('alice', { channel: 'GLOBAL', text: 'Three' }, '3')).resolves.toBeTruthy() })
  it('private rate limit is one second', async () => { const c = await setup(); await c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'One' }, '1'); await expect(c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'Two' }, '2')).rejects.toThrow(); c.advance(1000); await expect(c.chat.send('alice', { channel: 'PRIVATE', targetName: 'Bob', text: 'Three' }, '3')).resolves.toBeTruthy() })
  it('history is limited and cursor paginated', async () => { const c = await setup(); for (let index = 0; index < 4; index++) { await c.chat.send('alice', { channel: 'GLOBAL', text: String(index) }, `g${index}`); c.advance(2000) } const page = await c.chat.history('alice', { channel: 'GLOBAL', limit: 2 }); expect(page.messages).toHaveLength(2); expect(page.nextCursor).not.toBeNull(); const older = await c.chat.history('alice', { channel: 'GLOBAL', limit: 2, beforeMessageId: page.nextCursor! }); expect(older.messages[0].text).toBe('0') })
  it('persistent chat survives service reload', async () => { const c = await setup(); await c.chat.send('alice', { channel: 'GLOBAL', text: 'Persist' }, 'g'); const reloaded = new ChatService(new InMemoryPlayerRepository(c.database), c.presence, c.now); expect((await reloaded.history('bob', { channel: 'GLOBAL' })).messages[0].text).toBe('Persist') })
  it('leaving guild removes guild chat permission', async () => { const c = await setup(); await addRecruit(c); await c.guilds.leave('bob', 'leave'); await expect(c.chat.send('bob', { channel: 'GUILD', text: 'No' }, 'g')).rejects.toThrow() })
  it('combat lightweight group chat does not read social history', async () => { const c = await setup(); const before = c.database.operations.size; c.chat.groupMessage('alice', 'rift', 'Alice', 'Fight'); expect(c.database.operations.size).toBe(before) })
  it('duplicate message operation is idempotent', async () => { const c = await setup(); const first = await c.chat.send('alice', { channel: 'GLOBAL', text: 'Once' }, 'same'); const second = await c.chat.send('alice', { channel: 'GLOBAL', text: 'Once' }, 'same'); expect(second.id).toBe(first.id); expect(c.database.chatMessages).toHaveLength(1) })
})

describe('Phase 6 Presence', () => {
  it('connect status is online city', async () => { const c = await setup(); c.presence.set('alice', 'CITY'); expect(c.presence.isOnline('alice')).toBe(true) })
  it('disconnect status is offline', async () => { const c = await setup(); c.presence.set('alice', 'OFFLINE'); expect(c.presence.get('alice')).toBe('OFFLINE') })
  it('party lobby presence is represented', async () => { const c = await setup(); c.presence.set('alice', 'PARTY_LOBBY'); expect(c.presence.get('alice')).toBe('PARTY_LOBBY') })
  it('Rift presence is represented', async () => { const c = await setup(); c.presence.set('alice', 'RIFT'); expect(c.presence.get('alice')).toBe('RIFT') })
  it('friend snapshot receives presence update', async () => { const c = await setup(); await c.friends.sendRequest('alice', 'Bob', 'r'); const request = (await c.friends.state('bob')).incoming[0]; await c.friends.respond('bob', request.id, true, 'a'); c.presence.set('bob', 'RIFT'); expect((await c.friends.state('alice')).friends[0].status).toBe('RIFT') })
  it('guild roster shows online status', async () => { const c = await setup(); await addRecruit(c); c.presence.set('bob', 'OFFLINE'); expect((await c.guilds.state('alice')).members.find((value) => value.playerId === 'bob')?.online).toBe(false) })
})

describe('Phase 6 RoomManager social integration', () => {
  it('connect publishes social snapshots and City presence', async () => { const c = await setup(); const messages: ServerMessage[] = []; const manager = new RoomManager({ playerStates: c.players, economy: c.economy, presence: c.presence, friends: c.friends, guilds: c.guilds, chatService: c.chat, autoTimers: false }); await manager.connect({ playerId: 'alice' }, { connectionId: 'a', send: (message) => messages.push(message) }); expect(c.presence.get('alice')).toBe('CITY'); expect(messages.some((message) => message.type === 'GUILD_STATE')).toBe(true); expect(messages.some((message) => message.type === 'FRIENDS_STATE')).toBe(true); await manager.dispose() })
  it('party creation updates presence and party invite uses existing party flow', async () => { const c = await setup(); const bobMessages: ServerMessage[] = []; const manager = new RoomManager({ playerStates: c.players, economy: c.economy, presence: c.presence, friends: c.friends, guilds: c.guilds, chatService: c.chat, autoTimers: false }); await manager.connect({ playerId: 'alice' }, { connectionId: 'a', send: () => undefined }); await manager.connect({ playerId: 'bob' }, { connectionId: 'b', send: (message) => bobMessages.push(message) }); const room = manager.createParty('alice')!; await manager.handle('alice', { type: 'INVITE_TO_PARTY', payload: { playerId: 'bob' } }); expect(c.presence.get('alice')).toBe('PARTY_LOBBY'); expect(bobMessages.some((message) => message.type === 'PARTY_INVITE' && message.payload.partyId === room.id)).toBe(true); await manager.dispose() })
  it('active Rift rejects heavy social history while Group Chat remains available', async () => { const c = await setup(); const messages: ServerMessage[] = []; const manager = new RoomManager({ playerStates: c.players, economy: c.economy, presence: c.presence, friends: c.friends, guilds: c.guilds, chatService: c.chat, autoTimers: false }); await manager.connect({ playerId: 'alice' }, { connectionId: 'a', send: (message) => messages.push(message) }); const room = manager.createParty('alice')!; room.phase = 'COMBAT'; await manager.handle('alice', { type: 'GET_CHAT_HISTORY', payload: { channel: 'GLOBAL' } }); await manager.handle('alice', { type: 'PARTY_CHAT_MESSAGE', payload: { message: 'Fight' } }); expect(messages.some((message) => message.type === 'ERROR' && message.payload.code === 'SOCIAL_UNAVAILABLE_IN_RIFT')).toBe(true); expect(messages.some((message) => message.type === 'PARTY_CHAT_MESSAGE')).toBe(true); await manager.dispose() })
})
