import { useEffect, useState } from 'react'
import type { MultiplayerClient } from '../network/useMultiplayer'
const operationId = () => crypto.randomUUID()

export function FriendsPanel({ client }: { client: MultiplayerClient }) {
  const [name, setName] = useState('')
  const send = client.send
  useEffect(() => { send({ type: 'GET_FRIENDS_STATE' }) }, [send])
  const state = client.friends
  return <section className="city-content-panel social-panel"><header className="panel-heading"><div><p className="eyebrow">Social</p><h2>Друзі</h2></div><span>{state?.friends.filter((friend) => friend.online).length ?? 0} online</span></header><div className="social-grid two-columns"><div className="social-card"><h3>Знайти гравця</h3><div className="inline-form"><input value={name} placeholder="Точне ім’я" onChange={(event) => setName(event.target.value)} /><button onClick={() => client.send({ type: 'SEARCH_PLAYER', payload: { name } })}>Знайти</button></div>{client.playerSearch && <div className="social-row"><div><strong>{client.playerSearch.name}</strong><small>{client.playerSearch.classId} Lv.{client.playerSearch.level} · {client.playerSearch.status}</small></div><div className="row-actions"><button onClick={() => client.send({ type: 'SEND_FRIEND_REQUEST', payload: { playerName: client.playerSearch!.name, operationId: operationId() } })}>Додати</button><button className="ghost-button" onClick={() => client.send({ type: 'BLOCK_PLAYER', payload: { playerName: client.playerSearch!.name, operationId: operationId() } })}>Block</button></div></div>}<h3>Запити</h3>{state?.incoming.map((request) => <div className="social-row" key={request.id}><span>{request.player.name}</span><div className="row-actions"><button onClick={() => client.send({ type: 'ACCEPT_FRIEND_REQUEST', payload: { requestId: request.id, operationId: operationId() } })}>Прийняти</button><button className="ghost-button" onClick={() => client.send({ type: 'DECLINE_FRIEND_REQUEST', payload: { requestId: request.id, operationId: operationId() } })}>Відхилити</button></div></div>)}</div><div className="social-card"><h3>Список друзів</h3>{state?.friends.length ? state.friends.map((friend) => <div className="social-row" key={friend.playerId}><div><strong><i className={`presence-dot ${friend.online ? 'online' : ''}`} />{friend.name}</strong><small>{friend.classId} Lv.{friend.level} · {friend.status}</small></div><div className="row-actions"><button onClick={() => client.send({ type: 'SEND_CHAT_MESSAGE', payload: { channel: 'PRIVATE', targetName: friend.name, text: 'Привіт!', operationId: operationId() } })}>Message</button>{friend.online && <button className="ghost-button" onClick={() => client.send({ type: 'INVITE_TO_PARTY', payload: { playerId: friend.playerId } })}>У групу</button>}<button className="danger-button" onClick={() => client.send({ type: 'REMOVE_FRIEND', payload: { playerId: friend.playerId, operationId: operationId() } })}>×</button></div></div>) : <p>Список друзів порожній.</p>}<h3>Заблоковані</h3>{state?.blocked.map((player) => <div className="social-row compact" key={player.playerId}><span>{player.name}</span><button onClick={() => client.send({ type: 'UNBLOCK_PLAYER', payload: { playerId: player.playerId, operationId: operationId() } })}>Unblock</button></div>)}</div></div></section>
}
