import { useEffect, useState } from 'react'
import type { MultiplayerClient } from '../network/useMultiplayer'
import type { GuildRank } from '../../shared/social-types'
import { ITEM_CATALOG } from '../../shared/game-data/catalog'

interface Props { client: MultiplayerClient }
type GuildTab = 'overview' | 'members' | 'applications' | 'storage' | 'chat' | 'settings'
const operationId = () => crypto.randomUUID()

export function GuildPanel({ client }: Props) {
  const send = client.send
  const [tab, setTab] = useState<GuildTab>('overview')
  const [query, setQuery] = useState('')
  const [name, setName] = useState('')
  const [tag, setTag] = useState('')
  const [description, setDescription] = useState('')
  const [motd, setMotd] = useState('')
  const [inviteName, setInviteName] = useState('')
  const [applicationMessage, setApplicationMessage] = useState('')
  const [quantity, setQuantity] = useState(1)
  const [chatText, setChatText] = useState('')
  const guild = client.guild

  useEffect(() => { send({ type: 'GET_GUILD_STATE' }); send({ type: 'SEARCH_GUILDS', payload: {} }) }, [send])
  const guildId = guild?.guild?.id
  useEffect(() => {
    if (tab === 'storage' && guildId) { send({ type: 'GET_GUILD_STORAGE' }); send({ type: 'GET_GUILD_STORAGE_HISTORY', payload: { limit: 100 } }) }
    if (tab === 'chat' && guildId) send({ type: 'GET_CHAT_HISTORY', payload: { channel: 'GUILD' } })
  }, [tab, guildId, send])

  if (!guild) return <section className="city-content-panel social-panel"><p>Завантажуємо гільдії…</p></section>
  if (!guild.guild) return <section className="city-content-panel social-panel">
    <header className="panel-heading"><div><p className="eyebrow">Спільнота гравців</p><h2>Гільдії</h2></div><span>Створення: 500 coins</span></header>
    {guild.invites.length > 0 && <div className="social-card"><h3>Запрошення</h3>{guild.invites.map((invite) => <div className="social-row" key={invite.id}><div><strong>[{invite.guild.tag}] {invite.guild.name}</strong><small>Від {invite.invitedByName}</small></div><div className="row-actions"><button onClick={() => client.send({ type: 'ACCEPT_GUILD_INVITE', payload: { inviteId: invite.id, operationId: operationId() } })}>Прийняти</button><button className="ghost-button" onClick={() => client.send({ type: 'DECLINE_GUILD_INVITE', payload: { inviteId: invite.id, operationId: operationId() } })}>Відхилити</button></div></div>)}</div>}
    <div className="social-grid two-columns">
      <form className="social-card form-stack" onSubmit={(event) => { event.preventDefault(); client.send({ type: 'CREATE_GUILD', payload: { name, tag, description, messageOfTheDay: motd, operationId: operationId() } }) }}><h3>Створити гільдію</h3><label>Назва<input value={name} maxLength={40} onChange={(event) => setName(event.target.value)} required /></label><label>Тег<input value={tag} maxLength={8} onChange={(event) => setTag(event.target.value.toUpperCase())} required /></label><label>Опис<textarea value={description} maxLength={500} onChange={(event) => setDescription(event.target.value)} /></label><label>Message of the Day<input value={motd} maxLength={300} onChange={(event) => setMotd(event.target.value)} /></label><button className="primary-button">Створити</button></form>
      <div className="social-card"><h3>Пошук</h3><div className="inline-form"><input value={query} placeholder="Назва або тег" onChange={(event) => setQuery(event.target.value)} /><button onClick={() => client.send({ type: 'SEARCH_GUILDS', payload: { query } })}>Знайти</button></div><label>Повідомлення до заявки<input value={applicationMessage} maxLength={200} onChange={(event) => setApplicationMessage(event.target.value)} /></label><div className="social-list">{client.guildList.map((item) => <article className="social-row" key={item.id}><div><strong>[{item.tag}] {item.name}</strong><small>{item.memberCount}/{item.maxMembers} · {item.description || 'Без опису'}</small></div><button onClick={() => client.send({ type: 'APPLY_TO_GUILD', payload: { guildId: item.id, message: applicationMessage, operationId: operationId() } })}>Подати заявку</button></article>)}</div></div>
    </div>
  </section>

  const canManage = guild.selfRank === 'LEADER' || guild.selfRank === 'OFFICER'
  return <section className="city-content-panel social-panel">
    <header className="panel-heading"><div><p className="eyebrow">[{guild.guild.tag}]</p><h2>{guild.guild.name}</h2></div><span>{guild.guild.onlineCount} online · {guild.guild.memberCount}/{guild.guild.maxMembers}</span></header>
    <nav className="subtabs">{(['overview', 'members', 'applications', 'storage', 'chat', 'settings'] as GuildTab[]).filter((item) => item !== 'applications' || canManage).map((item) => <button className={tab === item ? 'active' : ''} key={item} onClick={() => setTab(item)}>{({ overview: 'Огляд', members: 'Учасники', applications: 'Заявки', storage: 'Сховище', chat: 'Чат', settings: 'Налаштування' } as const)[item]}</button>)}</nav>
    {tab === 'overview' && <div className="social-grid two-columns"><article className="social-card"><h3>Message of the Day</h3><p>{guild.guild.messageOfTheDay || 'Лідер ще не залишив повідомлення.'}</p></article><article className="social-card"><h3>Про гільдію</h3><p>{guild.guild.description || 'Опис відсутній.'}</p><small>Ваш ранг: {guild.selfRank}</small></article></div>}
    {tab === 'members' && <div className="social-card"><div className="inline-form"><input value={inviteName} placeholder="Точне ім’я гравця" onChange={(event) => setInviteName(event.target.value)} />{canManage && <button onClick={() => client.send({ type: 'INVITE_TO_GUILD', payload: { playerName: inviteName, operationId: operationId() } })}>Запросити</button>}</div><div className="social-list">{guild.members.map((member) => <article className="social-row" key={member.playerId}><div><strong><i className={`presence-dot ${member.online ? 'online' : ''}`} />{member.name}</strong><small>{member.classId} Lv.{member.level} · ATK {member.attack} · HP {member.maxHP} · {member.status} · {member.rank}</small></div><div className="row-actions">{member.online && member.playerId !== client.playerId && <button className="ghost-button" onClick={() => client.send({ type: 'INVITE_TO_PARTY', payload: { playerId: member.playerId } })}>У групу</button>}{guild.selfRank === 'LEADER' && member.playerId !== client.playerId && <><select value={member.rank === 'LEADER' ? 'OFFICER' : member.rank} onChange={(event) => client.send({ type: 'SET_GUILD_RANK', payload: { playerId: member.playerId, rank: event.target.value as Exclude<GuildRank, 'LEADER'>, operationId: operationId() } })}><option>OFFICER</option><option>MEMBER</option><option>RECRUIT</option></select><button className="ghost-button" onClick={() => client.send({ type: 'TRANSFER_GUILD_LEADERSHIP', payload: { playerId: member.playerId, operationId: operationId() } })}>Лідерство</button></>}{canManage && member.playerId !== client.playerId && member.rank !== 'LEADER' && <button className="danger-button" onClick={() => client.send({ type: 'KICK_GUILD_MEMBER', payload: { playerId: member.playerId, operationId: operationId() } })}>Виключити</button>}</div></article>)}</div></div>}
    {tab === 'applications' && <div className="social-card"><h3>Заявки</h3>{guild.applications.length === 0 ? <p>Нових заявок немає.</p> : guild.applications.map((application) => <article className="social-row" key={application.id}><div><strong>{application.player.name}</strong><small>{application.player.classId} Lv.{application.player.level} · ATK {application.player.attack} · HP {application.player.maxHP}</small><p>{application.message || 'Без повідомлення'}</p></div><div className="row-actions"><button onClick={() => client.send({ type: 'ACCEPT_GUILD_APPLICATION', payload: { applicationId: application.id, operationId: operationId() } })}>Прийняти</button><button className="ghost-button" onClick={() => client.send({ type: 'REJECT_GUILD_APPLICATION', payload: { applicationId: application.id, operationId: operationId() } })}>Відхилити</button></div></article>)}</div>}
    {tab === 'storage' && <div className="social-grid two-columns"><div className="social-card"><h3>Guild Storage</h3><label>Кількість<input type="number" min={1} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><h4>Ваш інвентар</h4>{client.characterState?.inventory.map((entry) => <div className="social-row compact" key={entry.entryId}><span>{ITEM_CATALOG[entry.itemId]?.name ?? entry.itemId} ×{entry.quantity}</span>{client.guildStorage?.canDeposit && <button onClick={() => client.send({ type: 'DEPOSIT_GUILD_STORAGE', payload: { entryId: entry.entryId, quantity, operationId: operationId() } })}>Deposit</button>}</div>)}<h4>Спільні предмети</h4>{client.guildStorage?.items.map((item) => <div className="social-row compact" key={item.id}><span>{item.icon} {item.name} ×{item.quantity}{item.attack ? ` · ATK +${item.attack}` : ''}{item.hp ? ` · HP +${item.hp}` : ''}</span>{client.guildStorage?.canWithdraw && <button onClick={() => client.send({ type: 'WITHDRAW_GUILD_STORAGE', payload: { storageItemId: item.id, quantity, operationId: operationId() } })}>Withdraw</button>}</div>)}</div><div className="social-card"><h3>History</h3>{client.guildStorageHistory.map((log) => <div className="history-line" key={log.id}><strong>{log.playerName}</strong> {log.action === 'DEPOSIT' ? 'поклав' : 'забрав'} {log.quantity} × {log.itemName}<small>{new Date(log.createdAt).toLocaleString('uk-UA')}</small></div>)}</div></div>}
    {tab === 'chat' && <div className="social-card chat-surface"><ChatFeed client={client} /><div className="chat-compose"><input value={chatText} maxLength={300} onChange={(event) => setChatText(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && chatText.trim()) { client.send({ type: 'SEND_CHAT_MESSAGE', payload: { channel: 'GUILD', text: chatText, operationId: operationId() } }); setChatText('') } }} /><button onClick={() => { if (chatText.trim()) { client.send({ type: 'SEND_CHAT_MESSAGE', payload: { channel: 'GUILD', text: chatText, operationId: operationId() } }); setChatText('') } }}>›</button></div></div>}
    {tab === 'settings' && <div className="social-grid two-columns"><div className="social-card form-stack"><h3>Guild settings</h3><label>Опис<textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Message of the Day<input value={motd} onChange={(event) => setMotd(event.target.value)} /></label>{guild.selfRank === 'LEADER' && <button onClick={() => client.send({ type: 'UPDATE_GUILD', payload: { description, messageOfTheDay: motd, operationId: operationId() } })}>Зберегти</button>}<button className="ghost-button" onClick={() => client.send({ type: 'LEAVE_GUILD', payload: { operationId: operationId() } })}>Leave Guild</button>{guild.selfRank === 'LEADER' && <button className="danger-button" onClick={() => client.send({ type: 'DISBAND_GUILD', payload: { confirmed: true, operationId: operationId() } })}>Підтвердити розпуск</button>}</div><div className="social-card"><h3>Storage permissions</h3>{guild.permissions.filter((permission) => permission.rank !== 'LEADER').map((permission) => <div className="permission-row" key={permission.rank}><strong>{permission.rank}</strong><label><input type="checkbox" checked={permission.canDeposit} onChange={(event) => client.send({ type: 'UPDATE_GUILD_PERMISSIONS', payload: { rank: permission.rank as Exclude<GuildRank, 'LEADER'>, canDeposit: event.target.checked, canWithdraw: permission.canWithdraw, operationId: operationId() } })} disabled={guild.selfRank !== 'LEADER'} /> Deposit</label><label><input type="checkbox" checked={permission.canWithdraw} onChange={(event) => client.send({ type: 'UPDATE_GUILD_PERMISSIONS', payload: { rank: permission.rank as Exclude<GuildRank, 'LEADER'>, canDeposit: permission.canDeposit, canWithdraw: event.target.checked, operationId: operationId() } })} disabled={guild.selfRank !== 'LEADER'} /> Withdraw</label></div>)}</div></div>}
  </section>
}

function ChatFeed({ client }: Props) { const messages = client.chatHistory?.channel === 'GUILD' ? client.chatHistory.messages : []; return <div className="social-chat-feed">{messages.map((message) => <p key={message.id}><span>{new Date(message.createdAt).toLocaleTimeString('uk-UA', { hour: '2-digit', minute: '2-digit' })}</span><strong>{message.senderName}</strong>{message.text}</p>)}</div> }
