import { useEffect, useMemo, useState } from 'react'
import { ITEM_CATALOG } from '../../shared/game-data/catalog'
import type { MultiplayerClient } from '../network/useMultiplayer'

export function MarketPanel({ client }: { client: MultiplayerClient }) {
  const send = client.send
  const [section, setSection] = useState<'market' | 'orders'>('market')
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('all')
  const [quantity, setQuantity] = useState(1)
  const [price, setPrice] = useState(1)
  useEffect(() => { send({ type: 'GET_MARKET' }) }, [send])
  const snapshot = client.market
  const items = useMemo(() => (snapshot?.items ?? []).filter((item) => (category === 'all' || item.category === category) && item.name.toLowerCase().includes(search.toLowerCase())), [snapshot, search, category])
  const selectedId = snapshot?.selectedItemId ?? items[0]?.itemId ?? null
  const selected = selectedId ? ITEM_CATALOG[selectedId] : null
  const inventory = client.characterState?.inventory.filter((entry) => entry.itemId === selectedId) ?? []
  const entry = inventory[0]
  const operationId = () => crypto.randomUUID()
  return <section className="city-content-panel market-panel">
    <div className="section-heading"><div><span>Server-authoritative exchange</span><h2>Market</h2></div><div className="market-tabs"><button className={section === 'market' ? 'active' : ''} onClick={() => setSection('market')}>MARKET</button><button className={section === 'orders' ? 'active' : ''} onClick={() => setSection('orders')}>MY ORDERS</button></div></div>
    <div className="wallet-strip"><span>Coins <strong>{client.characterState?.coins ?? 0}</strong></span><span>Reserved <strong>{client.characterState?.reservedCoins ?? 0}</strong></span><span>Available <strong>{client.characterState?.availableCoins ?? 0}</strong></span></div>
    {section === 'orders' ? <div className="market-orders">{snapshot?.myOrders.map((order) => <article key={order.id}><strong>{order.side} · {ITEM_CATALOG[order.itemId]?.name ?? order.itemId}</strong><span>{order.remainingQuantity}/{order.originalQuantity} @ {order.pricePerUnit}</span><em>{order.status}</em>{(order.status === 'OPEN' || order.status === 'PARTIALLY_FILLED') && <button onClick={() => client.send({ type: 'CANCEL_MARKET_ORDER', payload: { orderId: order.id, operationId: operationId() } })}>Cancel</button>}</article>)}</div> : <>
      <div className="market-browser"><div className="market-search"><input placeholder="Search item" value={search} onChange={(event) => setSearch(event.target.value)} /><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">All categories</option><option value="resource">Resources</option><option value="consumable">Consumables</option><option value="equipment">Equipment</option><option value="jewelry">Jewelry</option><option value="recipe">Recipes</option></select><div className="market-item-list">{items.map((item) => <button key={item.itemId} className={selectedId === item.itemId ? 'active' : ''} onClick={() => client.send({ type: 'GET_MARKET', payload: { itemId: item.itemId } })}><span>{item.icon}</span><strong>{item.name}</strong><small>Sell {item.lowestSell ?? '—'} · Buy {item.highestBuy ?? '—'}</small></button>)}</div></div>
      <div className="market-detail">{selected && <><div className="market-item-title"><span>{selected.icon}</span><div><h3>{selected.name}</h3><p>{selected.category} {selected.allowedClass ? `· ${selected.allowedClass}` : ''} {selected.attack ? `· ⚔ +${selected.attack}` : ''} {selected.hp ? `· ♥ +${selected.hp}` : ''}</p></div></div><div className="market-quote"><span>Lowest Sell <strong>{snapshot?.sellOrders[0]?.pricePerUnit ?? '—'}</strong></span><span>Highest Buy <strong>{snapshot?.buyOrders[0]?.pricePerUnit ?? '—'}</strong></span></div><div className="market-form"><label>Quantity<input type="number" min="1" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value)))} /></label><label>Price / unit<input type="number" min="1" value={price} onChange={(event) => setPrice(Math.max(1, Number(event.target.value)))} /></label><small>Total {quantity * price} coins</small><div><button onClick={() => client.send({ type: 'CREATE_BUY_ORDER', payload: { itemId: selected.id, quantity, pricePerUnit: price, operationId: operationId() } })}>Create Buy Order</button><button disabled={!snapshot?.sellOrders.length} onClick={() => client.send({ type: 'BUY_NOW', payload: { itemId: selected.id, quantity, operationId: operationId() } })}>Buy Now</button><button disabled={!entry} onClick={() => entry && client.send({ type: 'CREATE_SELL_ORDER', payload: { entryId: entry.entryId, quantity: Math.min(quantity, entry.quantity), pricePerUnit: price, operationId: operationId() } })}>Create Sell Order</button><button disabled={!entry || !snapshot?.buyOrders.length} onClick={() => entry && client.send({ type: 'SELL_NOW', payload: { entryId: entry.entryId, quantity: Math.min(quantity, entry.quantity), operationId: operationId() } })}>Sell Now</button></div></div><div className="order-books"><div><h4>SELL ORDERS</h4>{snapshot?.sellOrders.slice(0, 8).map((order) => <p key={order.id}><span>{order.remainingQuantity} × {order.pricePerUnit}</span><small>{order.playerName}</small></p>)}</div><div><h4>BUY ORDERS</h4>{snapshot?.buyOrders.slice(0, 8).map((order) => <p key={order.id}><span>{order.remainingQuantity} × {order.pricePerUnit}</span><small>{order.playerName}</small></p>)}</div></div><div className="market-history"><h4>RECENT TRADES</h4>{snapshot?.recentFills.map((fill) => <span key={fill.id}>{fill.quantity} × {fill.unitPrice} · {new Date(fill.createdAt).toLocaleTimeString()}</span>)}</div></>}</div></div>
    </>}
  </section>
}
