import { useMemo, useState } from 'react'
import type { MultiplayerClient } from '../network/useMultiplayer'
import { ITEM_CATALOG } from '../../shared/game-data/catalog'

export function TradePanel({ client }: { client: MultiplayerClient }) {
  const [receiverName, setReceiverName] = useState('')
  const [coins, setCoins] = useState(0)
  const [selected, setSelected] = useState<Record<string, boolean>>({})
  const trade = client.trade; const selfId = client.playerId
  const otherId = trade && selfId ? (trade.requesterId === selfId ? trade.receiverId : trade.requesterId) : null
  const myOffer = trade && selfId ? trade.offers[selfId] : null; const theirOffer = trade && otherId ? trade.offers[otherId] : null
  const offeredItems = useMemo(() => (client.characterState?.inventory ?? []).filter((entry) => selected[entry.entryId]).map((entry) => ({ entryId: entry.entryId, quantity: entry.quantity })), [client.characterState, selected])
  const op = () => crypto.randomUUID()
  if (!trade || trade.status === 'CANCELLED' || trade.status === 'DECLINED' || trade.status === 'COMPLETED') return <section className="city-content-panel trade-panel"><div className="section-heading"><div><span>Online players · exact name</span><h2>Direct Trade</h2></div></div>{trade?.status === 'COMPLETED' && <p className="trade-notice">Trade completed atomically.</p>}<label className="name-field"><span>Player name</span><input value={receiverName} onChange={(event) => setReceiverName(event.target.value)} /></label><button className="primary-button" disabled={!receiverName.trim()} onClick={() => client.send({ type: 'REQUEST_TRADE', payload: { receiverName: receiverName.trim(), operationId: op() } })}>Request Trade</button></section>
  if (trade.status === 'REQUESTED') { const incoming = trade.receiverId === selfId; return <section className="city-content-panel trade-panel"><h2>Trade request</h2><p>{trade.requesterName} wants to trade with {trade.receiverName}.</p>{incoming ? <div><button onClick={() => client.send({ type: 'ACCEPT_TRADE', payload: { tradeId: trade.id, operationId: op() } })}>Accept</button><button onClick={() => client.send({ type: 'DECLINE_TRADE', payload: { tradeId: trade.id, operationId: op() } })}>Decline</button></div> : <button onClick={() => client.send({ type: 'CANCEL_TRADE', payload: { tradeId: trade.id, operationId: op() } })}>Cancel request</button>}</section> }
  const selfConfirmed = trade.requesterId === selfId ? trade.requesterConfirmed : trade.receiverConfirmed
  const otherConfirmed = trade.requesterId === selfId ? trade.receiverConfirmed : trade.requesterConfirmed
  return <section className="city-content-panel trade-panel"><div className="section-heading"><div><span>Revision {trade.revision}</span><h2>{trade.requesterName} ↔ {trade.receiverName}</h2></div></div><div className="trade-offers"><div><h3>YOUR OFFER</h3>{myOffer?.items.map((item) => <p key={item.entryId}>{ITEM_CATALOG[item.itemId]?.icon} {ITEM_CATALOG[item.itemId]?.name} ×{item.quantity}</p>)}<strong>{myOffer?.coins ?? 0} coins</strong><em>{selfConfirmed ? 'Confirmed' : 'Editing'}</em></div><div><h3>THEIR OFFER</h3>{theirOffer?.items.map((item) => <p key={item.entryId}>{ITEM_CATALOG[item.itemId]?.icon} {ITEM_CATALOG[item.itemId]?.name} ×{item.quantity}</p>)}<strong>{theirOffer?.coins ?? 0} coins</strong><em>{otherConfirmed ? 'Confirmed' : 'Editing'}</em></div></div><p className="trade-notice">Changing either offer resets both confirmations.</p><div className="trade-inventory">{client.characterState?.inventory.map((entry) => <label key={entry.entryId}><input type="checkbox" checked={Boolean(selected[entry.entryId])} onChange={(event) => setSelected((current) => ({ ...current, [entry.entryId]: event.target.checked }))} />{ITEM_CATALOG[entry.itemId]?.name} ×{entry.quantity}</label>)}</div><label>Coins<input type="number" min="0" max={client.characterState?.availableCoins ?? 0} value={coins} onChange={(event) => setCoins(Math.max(0, Number(event.target.value)))} /></label><div className="trade-actions"><button onClick={() => client.send({ type: 'UPDATE_TRADE_OFFER', payload: { tradeId: trade.id, items: offeredItems, coins: Math.floor(coins), operationId: op() } })}>Update Offer</button><button className="primary-button" onClick={() => client.send({ type: 'CONFIRM_TRADE', payload: { tradeId: trade.id, revision: trade.revision, operationId: op() } })}>Confirm Trade</button><button onClick={() => client.send({ type: 'CANCEL_TRADE', payload: { tradeId: trade.id, operationId: op() } })}>Cancel</button></div></section>
}
